export const svgIcons = [
{ name:'bus', path:'/icons/bus-2-fill.svg' },
{ name:'film', path:'/icons/film-fill.svg' },
{ name:'hospital', path:'/icons/hospital-fill.svg' },
{ name:'lightbulb flash', path:'/icons/lightbulb-flash-fill.svg' },
{ name:'plane', path:'/icons/plane-fill.svg' },
{ name:'recycle', path:'/icons/recycle-fill.svg' },
{ name:'shopping cart', path:'/icons/shopping-cart-2-fill.svg' },
{ name:'train', path:'/icons/train-fill.svg' },
{ name:'water drop', path:'/icons/contrast-drop-2-line.svg' },
{ name:'graduation cap', path:'/icons/graduation-cap-fill.svg' },
{ name:'leaf', path:'/icons/leaf-fill.svg' },
{ name:'mickey', path:'/icons/mickey-fill.svg' },
{ name:'poker clubs', path:'/icons/poker-clubs-fill.svg' },
{ name:'service bell', path:'/icons/service-bell-fill.svg' },
{ name:'sun', path:'/icons/sun-fill.svg' },
{ name:'webcam', path:'/icons/webcam-fill.svg' },
{ name:'door lock', path:'/icons/door-lock-fill.svg' },
{ name:'heart', path:'/icons/heart-pulse-fill.svg' },
{ name:'lightbulb new', path:'/icons/lightbulb-ai-fill.svg' },
{ name:'movie', path:'/icons/movie-2-fill.svg' },
{ name:'radar', path:'/icons/radar-fill.svg' },
{ name:'shield check', path:'/icons/shield-check-fill.svg' },
{ name:'team', path:'/icons/team-fill.svg' },
{ name:'wifi', path:'/icons/wifi-line.svg' },
]